name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up branch name as TAG
      id: vars
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          TAG=${{ github.head_ref }}
        else
          TAG=${{ github.ref_name }}
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/elixir:${{ steps.vars.outputs.tag }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/elixir:${{ steps.vars.outputs.tag }}